//! The playing mode: a `Game` advanced by a fixed-timestep accumulator, plus
//! pause handling, the animated sprite sheets, the HUD and the level
//! clear / game over overlays.

use crate::game::{Action, CHARACTER_FRAMES, Game, GameSprites, State, TARGET_FRAMES};
use crate::palette::{self, BG, HUD};
use engine::color::Palette;
use engine::font;
use engine::input::{Input, InputState};
use engine::render::{Framebuffer, Renderer};
use engine::scene::{Scene, SceneAction};
use engine::sprites::{RleSprite, SpriteSheet};

/// Fixed simulation timestep: the game advances in fixed 1/60 s steps,
/// independently of the display refresh rate.
const FRAME_TIME: f64 = 1.0 / TARGET_FRAMES as f64;

/// Never run more than this many simulation steps per frame.
const MAX_SIM_STEPS: usize = 8;

// The fruit sprite sheet: 12 frames of 24x24 (one board cell) laid out
// horizontally in this crate's assets/apple_rotate.png.
const FRUIT_SPRITE: &str = "apple_rotate.png";
const FRAME_W: usize = 24;
const FRAME_H: usize = 24;
const FRUIT_FRAMES: usize = 12;

// The gibbon and guard sprite sheets: 5 frames each, generated by the
// `gen_assets` example (see examples/gen_assets.rs).
const GIBBON_SPRITE: &str = "gibbon.png";
const GUARD_SPRITE: &str = "guard.png";

const PAUSED_POS: (i32, i32) = (6, 16);

/// A selected game: owns the sprite sheets and the palette up front (created
/// at selection time, so memory is spent only for the chosen game), then owns
/// the `Game` once the player count is confirmed, plus the simulation
/// accumulator and the pause state.
pub struct Playing {
    game: Option<Game>,
    fruit: Vec<RleSprite>,
    gibbon: Vec<RleSprite>,
    guard: Vec<RleSprite>,
    /// The palette the sprites were quantized against; also the scene's
    /// palette, so framebuffer indices match the loaded sprites.
    palette: Palette,
    sim_accumulator: f64,
    paused: bool,
    pause_requested: bool,
    /// Whether each dig button was already held on the last update: a dig
    /// fires once per new press (GameA/F1 digs down-left, GameB/F2 digs
    /// down-right), not every frame the button stays held.
    dig_a_prev: bool,
    dig_b_prev: bool,
}

impl Playing {
    /// Decode one sprite sheet against the game palette, adding the sprites'
    /// colors to it.
    fn load_sprites(palette: &mut Palette, name: &str, frames: usize) -> Vec<RleSprite> {
        let data = crate::assets::load(name).expect("embedded sprite sheet must exist");
        SpriteSheet::from_png(data, palette, FRAME_W, FRAME_H, frames)
            .expect("embedded sprite sheet must load")
            .to_rle()
            .expect("sprite frames must encode to RLE")
    }

    /// Create the game instance: build the game palette (the 16 default colors
    /// plus the game's fixed colors), then decode the sprite sheets against it,
    /// which adds the sprites' colors to the palette. Called when the game is
    /// selected, before the player count is known; [`Playing::start`] creates
    /// the `Game` when the menu confirms.
    pub fn new() -> Playing {
        let mut palette = palette::palette();
        let fruit = Self::load_sprites(&mut palette, FRUIT_SPRITE, FRUIT_FRAMES);
        let gibbon = Self::load_sprites(&mut palette, GIBBON_SPRITE, CHARACTER_FRAMES);
        let guard = Self::load_sprites(&mut palette, GUARD_SPRITE, CHARACTER_FRAMES);
        Playing {
            game: None,
            fruit,
            gibbon,
            guard,
            palette,
            sim_accumulator: 0.0,
            paused: false,
            pause_requested: false,
            dig_a_prev: false,
            dig_b_prev: false,
        }
    }

    /// Create the game. Called once by the player count menu right before this
    /// scene becomes active; the gibbon is always single-player, so the player
    /// count is ignored.
    pub fn start(&mut self, _players: usize) {
        self.game = Some(Game::new());
    }
}

impl Default for Playing {
    fn default() -> Playing {
        Playing::new()
    }
}

impl Scene for Playing {
    fn input(&mut self, _player: usize, input: Input, down: bool) -> SceneAction {
        if !down {
            return SceneAction::Continue;
        }
        let game = self.game.as_mut().expect("game started before it ran");
        match input {
            Input::Pause => self.pause_requested = true,
            Input::Back => return SceneAction::PopToRoot,
            // Restart from level one when the run is over; irrelevant while
            // playing, clearing or dead.
            Input::Confirm => {
                if matches!(game.state, State::GameOver | State::Win) {
                    game.restart();
                }
            }
            // Directions are sampled as held state during `update`.
            Input::Up | Input::Down | Input::Left | Input::Right => {}
            Input::GameA | Input::GameB | Input::GameX | Input::GameY => {}
        }
        SceneAction::Continue
    }

    fn update(&mut self, dt: f64, input: &InputState) -> SceneAction {
        if self.pause_requested {
            self.pause_requested = false;
            self.paused = !self.paused;
        }

        if self.paused {
            return SceneAction::Continue;
        }

        let game = self.game.as_mut().expect("game started before it ran");

        // Pressing a direction sets the gibbon's latched movement direction:
        // it keeps walking, climbing or hanging in that direction even after
        // the key is released, until the way is blocked. Releasing all keys
        // does not stop it, so the game is only told about new directions.
        let up = input.held(0, Input::Up);
        let down = input.held(0, Input::Down);
        let left = input.held(0, Input::Left);
        let right = input.held(0, Input::Right);

        if up && !down {
            game.set_action(Some(Action::Up));
        } else if down && !up {
            game.set_action(Some(Action::Down));
        } else if left && !right {
            game.set_action(Some(Action::Left));
        } else if right && !left {
            game.set_action(Some(Action::Right));
        }

        // Dig fires on the press edge of a button: GameA/F1 digs the wooden
        // tile down-left, GameB/F2 the one down-right. Holding a button does
        // not dig again.
        let a = input.held(0, Input::GameA);
        let b = input.held(0, Input::GameB);

        if a && !self.dig_a_prev {
            game.dig(-1);
        }

        if b && !self.dig_b_prev {
            game.dig(1);
        }

        self.dig_a_prev = a;
        self.dig_b_prev = b;

        self.sim_accumulator += dt;

        let mut steps = 0;

        while self.sim_accumulator >= FRAME_TIME && steps < MAX_SIM_STEPS {
            game.step();
            self.sim_accumulator -= FRAME_TIME;
            steps += 1;
        }

        // Avoid carrying a huge backlog forever.
        if steps == MAX_SIM_STEPS {
            self.sim_accumulator = 0.0;
        }

        SceneAction::Continue
    }

    fn draw(&mut self, fb: &mut Framebuffer) {
        fb.clear(BG);
        let game = self.game.as_mut().expect("game started before it ran");
        let sprites = GameSprites {
            fruit: &self.fruit,
            gibbon: &self.gibbon,
            guard: &self.guard,
        };
        game.draw(fb, game.frame_cnt, &sprites);

        draw_hud(fb, game);

        if self.paused {
            fb.draw_text(PAUSED_POS.0, PAUSED_POS.1, 1, HUD, "PAUSED");
        }

        // Terminal and transitional overlays, drawn centered over the board.
        match game.state {
            State::Cleared => overlay(fb, "LEVEL CLEAR", 128),
            State::Dead => overlay(fb, "GOTCHA", 128),
            State::GameOver => {
                overlay(fb, "GAME OVER", 116);
                overlay(fb, "PRESS OK TO RESTART", 146);
            }
            State::Win => {
                overlay(fb, "YOU WIN", 116);
                overlay(fb, "PRESS OK TO RESTART", 146);
            }
            State::Playing => {}
        }
    }

    fn palette(&self) -> Palette {
        self.palette
    }

    fn clear_color(&self) -> engine::color::Color {
        BG
    }

    fn suspend(&mut self) {
        self.paused = true;
    }

    fn resume(&mut self) {
        self.paused = false;
        self.sim_accumulator = 0.0;
    }
}

/// Draw the level / fruit / lives line in the top HUD band, right-aligned so
/// it never collides with the engine's diagnostics on the left.
fn draw_hud(fb: &mut Framebuffer, game: &Game) {
    let text = format!(
        "LVL {}  FRUITS {}  LIVES {}",
        game.level_index + 1,
        game.fruits_left,
        game.lives
    );
    let width = font::text_width(&text, 1);
    fb.draw_text(480 - 6 - width, 6, 1, HUD, &text);
}

/// Center `text` horizontally and draw it at `y` (top-left of the line).
fn overlay(fb: &mut Framebuffer, text: &str, y: i32) {
    let width = font::text_width(text, 2);
    fb.draw_text((480 - width) / 2, y, 2, HUD, text);
}
