//! Embeds every file under `assets/` into the binary so the game can load
//! assets by file name on every platform (desktop, Android, tests) without
//! touching the filesystem at runtime.
//!
//! The generated module (in OUT_DIR) exposes `ASSETS: &[(&str, &[u8])]` keyed
//! by file name, plus a `load` helper is provided by `src/assets.rs`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let assets_dir = Path::new(&manifest_dir).join("assets");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let mut assets: Vec<(String, String)> = Vec::new();
    if assets_dir.is_dir() {
        for entry in fs::read_dir(&assets_dir).expect("read assets dir") {
            let entry = entry.expect("read assets entry");
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let name = path
                .file_name()
                .expect("asset file name")
                .to_string_lossy()
                .to_string();
            assets.push((name, path.to_string_lossy().to_string()));
        }
    }
    assets.sort();

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs; do not edit.\n");
    generated.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for (name, path) in &assets {
        generated.push_str(&format!("    ({:?}, include_bytes!({:?})),\n", name, path));
    }
    generated.push_str("];\n");

    fs::write(Path::new(&out_dir).join("assets.rs"), generated).expect("write generated assets");
}
